---
- name: stop and remove Apache
  hosts: srv-02.rhlab.ch
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
  become: yes

  tasks:
    - name: stop Apache
      service: name={{ apache }} state=stopped

    - name: remove Apache on RHEL
      yum:  name={{ apache }} state=absent
      when: ansible_os_family == "RedHat"

